export const TransactionTypes = {
  FETCHING_TRANSACTIONS: 'FETCHING_TRANSACTIONS',
  ADDING_TRANSACTIONS: 'ADDING_TRANSACTIONS',
  DELETING_TRANSACTIONS: 'DELETING_TRANSACTIONS',
  GET_TRANSACTIONS: 'GET_TRANSACTIONS',
  ADD_TRANSACTION: 'ADD_TRANSACTION',
  DETETE_TRANSACTION: 'DETETE_TRANSACTION',
  TRANSACTIONS_ERROR: 'TRANSACTIONS_ERROR',
};
